### ISSUE TITLE
serilog-sinks-console  in docker   Chinese garbled code appears, How to solve it

### ISSUE THREAD

**Issue by lkd3063601** [serilog/serilog-sinks-console#92] opened 2020-07-01 12:50 UTC
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).UseSerilog((context, configuration) =>
                {
                    configuration
                        .MinimumLevel.Warning()
                        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                        .Enrich.FromLogContext()
                        .WriteTo.Console(theme:ConsoleTheme.None)
                        .WriteTo.File(Path.Combine("logs", @"log.txt"), rollingInterval: RollingInterval.Day);
                });

![luama](https://user-images.githubusercontent.com/15059204/86245664-63377700-bbdc-11ea-86b5-c87b9f3106ee.png)

**Comment by nblumhardt** [comment] 2020-07-01 22:34
Duplicate of https://github.com/serilog/serilog/issues/1454

**Closed by nblumhardt** 2020-07-01 22:34 UTC
